apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-autenticacion
  namespace: default
  labels:
    app: front-autenticacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-autenticacion
  template:
    metadata:
      labels:
        app: front-autenticacion
    spec:
      containers:
      - name: front-autenticacion
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080


